- title: 'DevMeetMeat'
  date:  '16.08.2014'
  link: 'https://plus.google.com/events/cdp7ag1lct1cmbl2669ui1cjtfc?authkey=CISJ-OaZq7vi_wE'
  talks:
    - title: 'Наряжаем рельсу. Using decorators in Ruby on Rails'
      link: 'http://slides.kugaevsky.ru/using-decorators-in-ruby-on-rails.html'
      author: 'Nick Kugaevsky'
    - title: 'ExtJS 5 introduction'
      link: 'https://speakerdeck.com/noroot/extjs-5-introduction'
      author: 'Dmitry R'
    - title: 'Arduino Introduction and demo'
      link: 'http://overmind.ws/hardware/arduino/2013/09/05/arduino-music/'
      author: 'Dmitry R'
    - title: 'Erlang/OTP. Intro'
      link: 'https://github.com/r3nya/presentation_about_Erlang'
      author: 'Andrey M.'
      


- title: 'beta 3'
  date:  '04.07.2014'
  link: 'https://plus.google.com/events/c1p0a7ufo1stsapbhbq1p66redc?authkey=CKLS_5zfzNGtxgE'
  talks: 
    - title: 'Docker intro'
      link: 'https://speakerdeck.com/noroot/docker-introduction'
      author: 'Dmitry R'

- title: 'def self.tools'
  date:  '14.12.2013'
  link: 'https://plus.google.com/events/cfab8hgu94jh57ttjkehmktl1ss'
  talks:
    - title: 'Rails deploy using Ansible'
      link: 'https://github.com/r3nya/presentation_about_Rails_deploy'
      author: 'Andrey M.'
